<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7e3c855c-a2f7-4c4e-9341-a666fc795515</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arpasoft.TaskManagement.Application\Arpasoft.TaskManagement.Application.csproj" />
    <ProjectReference Include="..\Arpasoft.TaskManagement.Infrastructure\Arpasoft.TaskManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

</Project>
